# Generated by Django 5.1.5 on 2025-02-06 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEmissionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Catégorie')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom Client ou Société')),
                ('type_client', models.CharField(choices=[('Individuel', 'Individuel'), ('Entreprise Locale', 'Entreprise Locale'), ('Entreprise Étrangère', 'Entreprise Étrangère')], max_length=20, verbose_name='Type Client')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse Client ou Société')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('registre_commerce', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registre de Commerce')),
                ('assujetti_tva', models.BooleanField(default=False, verbose_name='Assujetti à la TVA')),
            ],
        ),
        migrations.CreateModel(
            name='StationRadioDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Station Département')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom Station Département')),
                ('categorie', models.CharField(choices=[('TV', 'TV'), ('Radio', 'Radio')], max_length=10, verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Émission')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom Émission')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.categorieemissionservice', verbose_name='Catégorie Emission/Service')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionDateEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(verbose_name="Date de l'Émission")),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.emission', verbose_name='Émission')),
            ],
            options={
                'unique_together': {('emission', 'date_emission')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code Service')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom Service')),
                ('taille', models.PositiveIntegerField(default=1, verbose_name='Taille (en secondes)')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.categorieemissionservice', verbose_name='Catégorie Emission/Service')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire')),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix Total')),
                ('emission_date_emission', models.ManyToManyField(to='FMInvoice.emissiondateemission', verbose_name='Émission/Date Émission')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='Emetteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=255, verbose_name='Nom Société')),
                ('type_societe', models.CharField(max_length=255, verbose_name='Type Société')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse Société')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nif', models.CharField(max_length=50, verbose_name='NIF')),
                ('registre_commerce', models.CharField(max_length=50, verbose_name='Registre de Commerce')),
                ('assujetti_tva', models.BooleanField(default=False, verbose_name='Assujetti à la TVA')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.stationradiodepartement', verbose_name='Station Radio Département')),
            ],
        ),
        migrations.AddField(
            model_name='categorieemissionservice',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.stationradiodepartement', verbose_name='Station Radio Département'),
        ),
        migrations.CreateModel(
            name='UtilisateurEmetteurStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stations', models.ManyToManyField(to='FMInvoice.stationradiodepartement', verbose_name='Stations où il travaille')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro Facture')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de Mise à Jour')),
                ('statut_validite', models.CharField(choices=[('Annulée', 'Annulée'), ('Valide', 'Valide')], default='Valide', max_length=10, verbose_name='Statut Validité')),
                ('statut_visibilite', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui', max_length=3, verbose_name='Statut Visibilité')),
                ('mode_paiement', models.CharField(choices=[('Caisse', 'Caisse'), ('Banque', 'Banque'), ('Crédits', 'Crédits'), ('Monnaie Électronique', 'Monnaie Électronique'), ('Autre', 'Autre')], max_length=20, verbose_name='Mode de Paiement')),
                ('type_facture', models.CharField(choices=[('Proforma', 'Proforma'), ('Déjà Payée', 'Déjà Payée'), ('En Cours', 'En Cours')], max_length=20, verbose_name='Type Facture')),
                ('devise', models.CharField(choices=[('BIF', 'BIF'), ('Dollars', 'Dollars'), ('Euro', 'Euro'), ('Autre', 'Autre')], max_length=20, verbose_name='Devise')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.client', verbose_name='Client')),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.emetteur', verbose_name='Émetteur')),
                ('lignes_commande', models.ManyToManyField(to='FMInvoice.lignecommande', verbose_name='Lignes de Commande')),
                ('emetteur_createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMInvoice.utilisateuremetteurstation', verbose_name='Émetteur Créateur')),
            ],
        ),
    ]
