# Generated by Django 5.1.5 on 2025-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMInvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date de l'émission")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emissiondateemission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Banque', 'Banque'), ('Crédits', 'Crédits'), ('Monnaie Électronique', 'Monnaie Électronique'), ('Autre', 'Autre')], max_length=20, verbose_name='Mode de Paiement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('Proforma', 'Proforma'), ('Payée', 'Payée'), ('En Cours', 'En Cours')], max_length=20, verbose_name='Type Facture'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Prix Total'),
        ),
        migrations.RemoveField(
            model_name='emissiondateemission',
            name='date_emission',
        ),
        migrations.AddField(
            model_name='emissiondateemission',
            name='date_emission',
            field=models.ManyToManyField(to='FMInvoice.dateemission', verbose_name="Dates de l'émission"),
        ),
    ]
